project:
  type: website

website:
  title: "uncommon stocks"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: instagram
        href: https://www.instagram.com/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



